# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master
- Dev

stages:
- stage: Build
  displayName: Build Stage
  jobs:
  - job: Build
    displayName: 'JavaScript Build Artifacts'
    pool:
      name: 'KratiPool'
      demands: 
        agent.name -equals Javascript_Agent
    steps:
    - task: ManualValidation@0
      inputs:
        notifyUsers: 'Cybage\ramyam'
        instructions: 'Please approve this stage.'
        onTimeout: 'reject'
    - task: NodeTool@0
      inputs:
        versionSource: 'spec'
        versionSpec: '20.x'
    - task: SonarCloudPrepare@1
      inputs:
        SonarCloud: 'SonarCloud'
        organization: 'kratib'
        scannerMode: 'CLI'
        configMode: 'manual'
        cliProjectKey: 'POC_JAPP'
        cliProjectName: 'POC_JAPP'
        cliProjectVersion: '$(Build.BuildNumber)'
        cliSources: '.'
        extraProperties: |
          sonar.exclusions=app/node_modules/*,app/coverage/lcov-report/*,app/test/integration/api/v1/*,app/middlewares/common-middleware.js
          sonar.javascript.lcov.reportPaths=coverage/lcov.info
    - task: Npm@1
      inputs:
        command: 'install'
    - task: Npm@1
      inputs:
        command: 'custom'
        customCommand: 'run build'
    - task: CmdLine@2
      inputs:
        script: 'npm install Jest -Dev--save'
    - task: Npm@1
      inputs:
        command: 'custom'
        customCommand: 'test'
    - task: SonarCloudAnalyze@1
      inputs:
        jdkversion: 'JAVA_HOME_17_X64'
    - task: SonarCloudPublish@1
      inputs:
        pollingTimeoutSec: '300'    